### ISSUE TITLE
all() method for edges results in None if no edges are found

### ISSUE THREAD

**Issue by dusktreader** [ZEROFAIL/goblin-legacy#16]
The all() method results in a value of None from the stream future if no results are found. 

Here is an example piece of code:

``` python
from goblin import properties
from goblin import connection
from goblin.models import Vertex, Edge

import inflection
import asyncio
from tornado.platform.asyncio import AsyncIOMainLoop


@asyncio.coroutine
def drop():
    stream = yield from Vertex.all()
    vertices = yield from stream.read()
    for vertex in vertices:
        yield from vertex.delete()
if __name__ == '__main__':
    connection.setup('ws://localhost:8182', future_class=asyncio.Future)
    AsyncIOMainLoop().install()
    loop = asyncio.get_event_loop()
    try:
        print("dropping")
        loop.run_until_complete(drop())
        loop.run_until_complete(drop())
        print("ending")
    except Exception as err:
        print("Caught an errror: {}".format(err))
        raise err
    finally:
        connection.tear_down()
        loop.close()
```

Executing this code will result in the follow exception:

```
TypeError: 'NoneType' object is not iterable
```

The result from the all method's stream should be an empty list so that an iteration over results where no matches are found does not raise an exception

**Comment by davebshow** [comment]
I must admit, I am a bit confused by title of this issue. I assume you mean "all() method for vertices". This should be fixed by commit 8afd422ee59797ad16254e34188f56b16cb1f304. Thanks for reporting.

**Comment by dusktreader** [comment]
Sorry about the mis-wording. I was a bit fatigued when I submitted the issue. I'm verifying the patch now.

**Comment by dusktreader** [comment]
I've verified that this fixed the issue. Thanks!

**Comment by davebshow** [comment]
Thank you for reporting @dusktreader!
