### ISSUE TITLE
Goblin property review/comparison with Titan

### ISSUE THREAD

**Issue by davebshow** [ZEROFAIL/goblin-legacy#22]
It's time to update Goblin's property management to improve integration with Titan.

To review there are currently a wide variety of properties that map between Python and Titan as follows:

| Goblin | Python 2/3 | Titan |
| --- | --- | --- |
| String | String | String |
| Short | Int | Short |
| Integer | Long/Integer | Integer |
| Positive Integer | Long/Integer | Integer |
| Long | Long/Integer | Long |
| Positive Long | Long/Integer | Long |
| Double | Float | Double |
| Float | Float | Float |
| UUID | String | String |
| Decimal | Decimal | Decimal/Precision (3/6 dig) |
| Dictionary | Dictionary | N/A |
| List | List | N/A |
| URL | String | String |
| DateTimeNaive | Datetime | Date? |
| DateTime | Datetime | Date? |
| Boolean | Boolean | Boolean |
| Slug | String | String |
| IPV4/6/4w/6 | String | String |

Most of these properties map simply and only needed to be tested against a graph db with appropriate schema definition. However, there are a few things to consider:

You may note that dictionary and list no longer have corresponding data types in Titan, instead, you can define a property data type as well as a cardinality--single, list, or set. We'll need to provide an API that allows the user to set the cardinality. 

Furthermore, the current Titan native data types make a distinction between 3/6 digit decimals (Decimal and Precision), and we should probably reflect this either by providing kwarg options or separate property classes.

The slug property doesn't do any slugification, something that may be of interest...

Also, the geoshape type will need to be implemented.

I haven't double checked yet how Titan handles the Date data type. Mogwai sent unix timestamps. Any input on the API, needed properties, anything...?

@jsenecal @leifurhauks?

**Comment by jsenecal** [comment]
Hey @davebshow, just to write down what we discussed yesterday:

Slugs should work in a similar fashion than in django, the method the implemented by their team is over [here](https://github.com/django/django/blob/master/django/utils/text.py#L417) but I think our project could benefit from a more advanced implementation like the [django-autoslug](https://github.com/neithere/django-autoslug/) project. (I used to heavily subclass the latter in my projects to do dynamically generated human meaningful ids for labels and such.)

For IPV4/6/4w/6 stuff, Python 3 should use its own [ipaddress library](https://docs.python.org/3/library/ipaddress.html#module-ipaddress) to represent ips and subnets; Py2.6/7 should use https://bitbucket.org/kwi/py2-ipaddress/ or https://github.com/phihag/ipaddress for API consistency.
Titan should store IPAddresses as integers and Networks as two-tuples of an address integer and a netmask integer (or equivalent structure if possible... This could also be two different fields linked somehow...)

:+1:

**Comment by jsenecal** [comment]
Also, in regards of your Geoshape comment, I think the best way to go would be to use the GDAL libraries for python representation as they are widely adopted by the various mapping communities.

**Comment by leifurhauks** [comment]
Currently, the UUID property type in goblin uses a str/unicode python representation. I think it might make sense to use a native python uuid object instead.

I agree with @jsenecal that slugification would be desirable. It should, however, be possible to use the slug property type to validate slugs without using the automatic slugification. There are certainly use cases where a goblin app is getting already constructed slugs from an outside source.

**Comment by davebshow** [comment]
You're right Leif, currently UUID are handled as strings on both ends. I updated the table.

**Comment by leifurhauks** [comment]
I was looking at the Date(Time) stuff yesterday -- titan has two native property types for them: [java.time.Instant](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html) and [java.util.Date](https://docs.oracle.com/javase/8/docs/api/java/util/Date.html).

I opened #30 which adds a date type; the only difference between this and the existing `DateTime` property type is that its value in python is a `datetime.date` instead of a `datetime.datetime`. It would of course be possible to use a `DateTime` for a property that is defined in the titan schema as a `Date`, it would just mean that the hours/minutes/seconds etc would be ignored by titan.
