### ISSUE TITLE
Create a vertex without a label

### ISSUE THREAD

**Issue by colleen-love** [ZEROFAIL/goblin-legacy#26]
Is there a way to create a vertex sans label?

I've tried overriding Vertex's get_label in order to return None or '' but those both threw exceptions. I'm using goblin with an existing database which does not have any vertex labels (and has a strict schema which does not permit label creation on the fly).

**Comment by davebshow** [comment]
Currently there is not. Labels are created automatically upon Vertex creation, and objects returned from the database require a label for deserialization. 

I'm curious about your uses case though. Maybe you could describe what you would like to do with Goblin and we can see the implications and from there determine if we can support it. The initial problem I can see would be property deseriallization: if we don't know what property types to expect based on the node label, we don't know how to deserialize them properly.

**Comment by colleen-love** [comment]
Ah - I understand. Currently there is a different property in the database which is used to identify which vertex is which type. Additionally the relationships are unique between types - only User vertices are adjacent to Company vertices by the edge with the label type 'represents'.

It's not a big push for us to switch over the 'type' property over to a vertex label. It probably makes more sense from a usability point of view as well.

**Comment by davebshow** [comment]
If it is an easy switch, that would probably be the best way to handle it.

**Comment by colleen-love** [comment]
Yeah - poking through the goblin code it doesn't look like it'd be a simple thing for which to add support. Thanks.
