### ISSUE TITLE
Moving forward with Goblin - Utilities for working with Titan:db schema and indices

### ISSUE THREAD

**Issue by davebshow** [ZEROFAIL/goblin-legacy#3]
Hello everyone! I would like to discuss some plans for moving forward with goblin. The are some implementation details that still need some work, like error handling, logging, etc.,  but the library is basically up and running. The next big hurdle will be figuring out how to implement some tools for working with Titan's modelling API. I noticed that Cody implemented some model syncing functionality in the original mogwai library, but I haven't looked too closely at it, and I don't know if it ever was actually integrated into the main library.

My initial thought is to provide a series of functions that can perform schema definitions supported by Titan:db [1]. Basically, we would be able to:
1. Create new elements (vertex, edge, property), and define their data types as well as cardinality.
2. Change element names (Titan does not allow changing data type etc.).
3. Define static vertices, TTL and undirected edges [2].

Regarding the implementation of this functionality, I want to do something like already suggested by the original mogwai design. The process would be something like this:

``` python
>>> generate_specfile(path_to_model_definition="models.py", ...)
```

The `generate_specfile` function inspects the file containing the `goblin` model definition and creates a simple JSON style data structure that contains the vertices, edges, and associated properties, which is dumped to a file `current_spec.json`.

```
"[{
    "verticies": [{"label": "person", ..., "properties": []}]
    "edges": ...
}]"
```

We then check to see if there is already a spec file associated with the app. If there is, we do a series of simple comparisons to check if there are:
1. Missing Vertices/Edges/Properties
2. New Vertices/Edge/Properties

``` python
>>> sync_spec(new_specfile, old_specfile)
```

If there are missing properties, we add this to a list of unused properties that can be reused. Missing vertices/edges are cataloged as unused elements. If there are "new properties" (could be an old property with a name change), we look through the unused properties. If there is an unused property with the proper data type and cardinality, we can recycle it by changing its name using Titan's API. If there are new vertices/edges, they will be created. Optionally, we could allow the user to pass element renaming mappings to allow name changes on vertices and edges, or other functionality to help the process along.

Finally, we output a new spec file that reflects the current state of the Schema, which includes the name changes made during the sync, as well as all of the unused elements.

Of course, if this is the first sync, we simply create the schema based on the specfile,

While this system isn't perfect, it could be pretty handy, especially for adding new models or simple property name changes.

Regarding indices [3], I assume we would like to allow the user to define their own indices on the models, which will be created on model sync. Elements created before index definition can be easily reindexed. 

Any ideas @jsenecal or @leifurhauks?
1. http://s3.thinkaurelius.com/docs/titan/1.0.0/schema.html
2. http://s3.thinkaurelius.com/docs/titan/1.0.0/advanced-schema.html
3. http://s3.thinkaurelius.com/docs/titan/1.0.0/indexes.html

**Comment by jsenecal** [comment]
Hey @davebshow, I think all this makes a lot of sense, it would also give a way nice way to move from one spec to another... It's also nice because you could store the various schema states in some directory/files. We don't need full fledged forward/backward "migrations" per se as i don't recall that titandb cares about schema. We would need goblin to react properly though if an expected vertice, edge, or associated properties is/are missing. 

Do I make any sense ?

@leifurhauks anything to add ?

**Comment by leifurhauks** [comment]
This sounds like a good system to me!

**Comment by davebshow** [comment]
@jsenecal what would be the expected behaviour in the case that the old spec includes a class (Vertex or Edge) that is missing from the new spec?

**Comment by jsenecal** [comment]
I'm guessing that the proper thing to do would be to behave in a way that lets the end user choose what to to. 

```
Edge/Vertex `ABC` is missing from the new spec file, [R]emove,[K]eep,[C]ancel all instances from the database? (r/k/c)
```
