### ISSUE TITLE
No VERSION file when I "pip install git+https://github.com/ZEROFAIL/goblin.git@dev"

### ISSUE THREAD

**Issue by TedMorris54** [ZEROFAIL/goblin-legacy#4]
I am a former Mogwai user and am excited to try out goblin.  When I pip-ed into my python environment, discovered the VERSION file was not present.  I added it manually and am moving forward, but thought you should know.

Upon further examination, it appears all of the files considered Unix executables - edge.groovy, vertex.groovy, LICENSE, Makefile, MANIFEST.in ... are all missing.

**Comment by davebshow** [comment]
Yes I made a basic fixYes I have been playing around with the library this afternoon, you should now be able to install the dev branch (with the executables) like such:

```
$ pip install git+https://github.com/ZEROFAIL/goblin.git@dev#egg=goblin
```

We are still getting everything setup. Thanks for your patience and help!

**Comment by davebshow** [comment]
I will lazily assume that this works for you and close the issue, unless it doesn't....

**Comment by TedMorris54** [comment]
Just tried it again, and I'm still having the same problem ...  I am pip-ing into a server install of python 3.5.  Later today I will set up a local image to see if I can get it to work.

Thanks for following up!

**Comment by leifurhauks** [comment]
I'm able to reproduce this:

```
(goblin-tmp-env) leifurpc% pip install git+https://github.com/ZEROFAIL/goblin.git@dev#egg=goblin
Collecting goblin from git+https://github.com/ZEROFAIL/goblin.git@dev#egg=goblin
  Cloning https://github.com/ZEROFAIL/goblin.git (to dev) to /tmp/pip-build-rwjdck16/goblin
```

(more pip output from collecting dependencies...)

```
Installing collected packages: pyparsing, pytz, tornado, gremlinclient, six, python-dateutil, fake-factory, factory-boy, pyformance, zope.interface, Twisted, goblin
  Running setup.py install for goblin ... done
Successfully installed Twisted-15.5.0 factory-boy-2.6.1 fake-factory-0.5.6 goblin-0.0.2 gremlinclient-0.2.1 pyformance-0.3.2 pyparsing-2.1.0 python-dateutil-2.5.0 pytz-2015.7 six-1.10.0 tornado-4.3 zope.interface-4.1.3

(goblin-tmp-env) leifurpc% python
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import goblin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lasgeirsson/.virtualenvs/goblin-tmp-env/lib/python3.5/site-packages/goblin/__init__.py", line 4, in <module>
    __version__ = open(__goblin_version_path__, 'r').readline().strip()
FileNotFoundError: [Errno 2] No such file or directory: '/home/lasgeirsson/.virtualenvs/goblin-tmp-env/lib/python3.5/site-packages/goblin/VERSION'
>>>
```

**Comment by TedMorris54** [comment]
@leifurhauks That is exactly the same error I see.

**Comment by davebshow** [comment]
Ah haha yes, I guess I am still used to seeing mogwai instead of goblin...I changed the MANIFEST.in recursive-include directory to goblin. Things seem to be working now. Would you guys mind confirming? Thanks again for reporting.

**Comment by TedMorris54** [comment]
I have just re-pip-ed and all appears to well.  Thank you @davebshow

**Comment by davebshow** [comment]
Thank you @TedMorris54 @leifurhauks for all the help! Please let me know if you have any questions/ideas etc.
