### ISSUE TITLE
Goblin Docs

### ISSUE THREAD

**Issue by davebshow** [ZEROFAIL/goblin-legacy#7]
Before I add the new functionality for schema and indices management, I think we should provide some simple documentation that covers goblin's core functionality, both to help our current users get going and attract new users/contributors. The first step in getting going will be updating the gremlinclient docs, as I would like to provide good cross referencing to help goblin users understand how to customize their goblin app. This will be relatively quick, but the goblin docs will be a bit more work. Before I put the time in, I want to make sure we are all on the same page.

I plan on using Sphinx to generate the documentation and host the docs on readthedocs, pretty standard, but there are other options for hosting as well...I usually use the alabaster theme, but I am open to suggestions here...

Relevant API documentation will be auto-generated by Sphinx from the docstrings, but I think it is important to include hand written docs with examples as well. I was thinking a basic structure like this:
- Home/Getting Started
- User Guides
  - The Basics - Defining Models and Creating Vertices and Relationships
  - Vertex and Relationship Objects API
  - The Relationship API - Adding Relationships to Vertex Models
  - Vertex Centric Queries
- Choosing a Websocket Client - Tornado, Aiohttp, Pulsar, Requests
- Schema and Index Management (coming soon)
- API autodocs
  ...

Comments or suggestions @jsenecal @leifurhauks?

**Comment by leifurhauks** [comment]
Looks good to me!

**Comment by jsenecal** [comment]
Same here - I think you got us covered @davebshow  :)

**Comment by blackboxx** [comment]
I really need docs

**Comment by davebshow** [comment]
well @blackboxx  there are docs up, they aren't as extensive as I'd like yet, but they should help: http://goblin.readthedocs.io/en/latest/index.html

I would currently recommend installing directly from the dev branch on github (not pypi).

**Comment by blackboxx** [comment]
Thank you @davebshow! Docs really helped now. I spent 4-9 hours trying to understand how can i just get Person.all() which is was not working before i switched to dev branch and Tripple-checked docs.  [My Question](http://stackoverflow.com/questions/37011951/no-such-property-v-for-class) . 

I also think for this project, I want to implement a Socket-connection Pool like Meteor DDP has.

**Comment by davebshow** [comment]
Hey @blackboxx I also updated the example in the docs to demonstrate the pattern for handling streaming results: http://goblin.readthedocs.io/en/latest/usage.html#creating-models

Hopefully before long I will be adding more examples.

btw, while I'm not familiar with Meteor DDP, Goblin reuses websocket connections using a `gremlinclient.Pool` object...

**Comment by blackboxx** [comment]
@davebshow , I dreaming it will be nice to have following feature:
We describing our models api in ddp.py file and after that we have Persons.all() method in JS!
[Django DDP](https://github.com/django-ddp/django-ddp) 
Furthermore, if someone will add a person, a person will appear on a web-page without reloading persons or page. It is possible because of Sockets connection.
I believe DDP is a next level after REST-like frameworks, such as django-rest or tastypie.

**Comment by davebshow** [comment]
Again, I'm not really familiar with DDP (Django or Meteor), but it seems to me that this would be best as an extension to the project, instead of being included in the core goblin software...
