### ISSUE TITLE
Vertex.get : unexpected exception for nonexistent ID

### ISSUE THREAD

**Issue by leifurhauks** [ZEROFAIL/goblin-legacy#8]
Calling Vertex.get with a nonexistent ID doesn't raise a DoesNotExist as expected.

When I run this script:
https://gist.github.com/leifurhauks/34c8e4d28025cd579af6

I get the following output:

```
leifurpc% python silly_script.py
INFO:__main__:set up goblin connection
INFO:__main__:Created person: Person(label=person, id=40972480, values={'name': 'Margaretta Heathcote DDS', 'url': 'http://www.jenkins.info/', 'email': 'dorathea.heathcote@gmail.com'})
INFO:__main__:ID: 40972480
INFO:__main__:Got a copy of person by id: Person(label=person, id=40972480, values={'name': 'Margaretta Heathcote DDS', 'url': 'http://www.jenkins.info/', 'email': 'dorathea.heathcote@gmail.com'})
ERROR:asyncio:Exception in callback Stream._read.<locals>.parser.<locals>.<lambda>(<Task finishe...> result=None>) at /home/lasgeirsson/.virtualenvs/noss-graphdb/lib/python3.5/site-packages/gremlinclient/connection.py:330
handle: <Handle Stream._read.<locals>.parser.<locals>.<lambda>(<Task finishe...> result=None>) at /home/lasgeirsson/.virtualenvs/noss-graphdb/lib/python3.5/site-packages/gremlinclient/connection.py:330>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/lasgeirsson/.virtualenvs/noss-graphdb/lib/python3.5/site-packages/gremlinclient/connection.py", line 330, in <lambda>
    lambda f: future.set_exception(e))
NameError: free variable 'e' referenced before assignment in enclosing scope

```

**Comment by davebshow** [comment]
Thanks Leif. I'll take a look at this later this afternoon.

**Comment by leifurhauks** [comment]
I think this case isn't being handled by goblin, but I'm also confused by the resulting exception from gremlinclient. Looking at [gremlinclient.connection:330](https://github.com/davebshow/gremlinclient/blob/master/gremlinclient/connection.py#L330), `e` looks like it should be in scope.

**Comment by davebshow** [comment]
Hey @leifurhauks I've got a really busy day today and I haven't had a chance to look into this very much. It's funny, because this case is tested and passes with the tornado_client [1], so I assume that it has something to do with the way I am adding the parser as a callback to aiohttp's receive method. Hopefully, I'll have some time to setup a trace a bit later this afternoon. If not, I'll check it out tomorrow for sure.

https://github.com/ZEROFAIL/goblin/blob/dev/goblin/tests/models/vertex_io_tests.py#L121

**Comment by leifurhauks** [comment]
Sounds good, but before you spend too much time troubleshooting it, that test you linked covers the case where a `DoesNotExist` is expected when trying to _delete_ a nonexistent vertex, which I can confirm works as expected with aiohttp. The problem I'm encountering is when using `MyVertexClass.get(id=<nonexistent_id>)`, which I think may not be covered.

I just noticed that in [`TestVertexIO.test_get_by_id`](https://github.com/ZEROFAIL/goblin/blob/dev/goblin/tests/models/vertex_io_tests.py#L200_), the case where the supplied id is `None` is tested (I can confirm that works on aiohttp), but a not-`None` nonexistent id doesn't seem to be tested.

I can add the failing test case in a PR, hopefully that will shed some light on this.

**Comment by davebshow** [comment]
??? In `test_model_deleting_works_properly` the vertex is first deleted, the test calls:

``` python
resp = yield TestVertexModel.get(vid)
```

Which should have the exact same result as calling:

``` python
SomeVertexClass.get("id_that_doesnt_exist")
```

Or maybe I have had a really long week...

**Comment by davebshow** [comment]
Also, I have isolated the problem to: https://github.com/davebshow/gremlinclient/blob/master/gremlinclient/aiohttp_client/client.py#L98

I am trying to determine the best way to fix this.

Thanks again!

**Comment by leifurhauks** [comment]
Ooof, I think I've had a long week, I've apparently forgotten how to read

**Comment by davebshow** [comment]
In the end I blame our mission for Python 2 compat...all these callbacks and futures are a pain, when we really should be using `yield from`

**Comment by leifurhauks** [comment]
Oh, it looks like you were already looking at a similar problem?
https://github.com/ZEROFAIL/goblin/blob/dev/goblin/tests/models/vertex_io_tests.py#L213
in that case you've indicated that there's a `RuntimeError` for calling get on a nonexistent ID

**Comment by davebshow** [comment]
No, the problem is the error info doesn't make it into the scope of the callback `release` future. The best way to handle this may be to explicitly pass exception info to close via a kwarg. But I'm still thinking on this...

**Comment by davebshow** [comment]
This should be fixed...at least in `gremlinclient`; however, may not get the error you are expecting from `goblin`. Error handling is currently a huge wart on both of the libraries. At least though now you shouldn't be getting the weird context error. Mind giving it a try?

**Comment by davebshow** [comment]
Btw, it is kind of a hacky fix...I will reassess when I take care of error handling in general.

**Comment by davebshow** [comment]
Actually better now, really simple fix in gremlinclient: https://github.com/davebshow/gremlinclient/blob/master/gremlinclient/connection.py#L321

**Comment by leifurhauks** [comment]
Ah, nice! That was a subtle issue. Is `e` not bound in the scope of the lambda?

**Comment by leifurhauks** [comment]
It now works as expected for me, thanks for all your help!

**Comment by davebshow** [comment]
No worries @leifurhauks thanks for finding this bug. If understand correctly, it is because using `Exception as e` is like a context manager in that the reference to `e` is removed upon exiting the error handler. However, locally defined variables can be passed in the callback....make sense? Sometimes I am better at doing that talking about this stuff...

**Comment by leifurhauks** [comment]
Ah okay, that makes sense.
