### ISSUE TITLE
DateTime type doesn't take a datetime

### ISSUE THREAD

**Issue by rotten** [ZEROFAIL/goblin-legacy#9]
Here is a simple code sample:

```

from goblin import properties
from goblin.models import Vertex, Edge, V
from goblin.connection import setup, close_global_pool

from datetime import datetime

class myVx(Vertex):

    someString   = properties.String()
    someDateTime = properties.DateTime()

setup("localhost")

myDT = datetime.now()

myNewVx = myVx.create(someString = "Hello World",
                      someDateTime = myDT)


```

I was surprised when I got this exception:

```
Traceback (most recent call last):
  File "vxtest.py", line 17, in <module>
    someDateTime = myDT)
  File "/some/path/.virtualenvs/goblin/lib/python3.5/site-packages/goblin/models/element.py", line 258, in create
    return cls(*args, **kwargs).save(**query_kwargs)
  File "/some/path/.virtualenvs/goblin/lib/python3.5/site-packages/goblin/models/element.py", line 69, in __init__
    value = prop.to_python(value)
  File "/some/path.virtualenvs/goblin/lib/python3.5/site-packages/goblin/properties/properties.py", line 227, in to_python
    float(value)).replace(tzinfo=utc)
TypeError: float() argument must be a string or a number, not 'datetime.datetime'

```

When I look at the relevant block of code in properties.py:

```
    def to_python(self, value):
        try:
            if isinstance(value, datetime.datetime):
                if value.tzinfo == utc:
                    return self.validator(value)  # .astimezone(tz=utc)
                else:
                    return self.validator(value).astimezone(tz=utc)
        except Exception as e:  # pragma: no cover
            # this shouldn't happen unless the validator has changed
            pass
        return datetime.datetime.utcfromtimestamp(
            float(value)).replace(tzinfo=utc)

```

If I expose the exception that is actually being thrown:

```
  File "/some/path/.virtualenvs/goblin/lib/python3.5/site-packages/goblin/properties/validators.py", line 170, in __call__
    self.message.format(value), code=self.code)
goblin.exceptions.ValidationError: Not a valid UTC DateTime: 2016-03-21 17:08:39.149907
```

So, looking at that block of code, I end up in this try/except chain:

```
            # print_("Got value with timezone: {} - {}".format(value, value.tzinfo))
            try:
                value = value.astimezone(tz=utc)
            except ValueError:  # last ditch effort
                try:
                    value = value.replace(tz=utc)
                except (AttributeError, TypeError):
                    raise ValidationError(
                        self.message.format(value), code=self.code)
            except AttributeError:  # pragma: no cover
                # This should never happen, unless it isn't a datetime object
                raise ValidationError(self.message % (value, ), code=self.code)
```

_value.astimezone(tz=utc)_ fails with the exception:
   **ValueError: astimezone() cannot be applied to a naive datetime**

So that drops to _value.replace(tz=utc)_, which fails with the exception:
    **TypeError: 'tz' is an invalid keyword argument for this function**

And that is probably because the keyword is supposed to be _tzinfo_ .

All of that analysis makes me wonder if the default behavior, when passing in a timezone-naive datetime, should be to assume UTC, or should it assume "Local Timezone" before stashing it in the database?  Perhaps a warning could be issued?

FWIW, to default to the local timezone I, usually do this quick and dirty approach:

```
from tzlocal import get_localzone
from datetime import datetime

myDT = datetime.now()
myDT = myDT.replace(tzinfo = get_localzone())

```

... and when I add that to my example above, the new vertex is successfully created (because it bypasses the faulty validator code).

**Comment by davebshow** [comment]
Thanks @rotten. Yes, the keyword for `datetime.replace` should be `tzinfo`-willfix. I haven't looked into properties much since I started the port, but they are on the todo list. Regarding the default behavior, I'll have to think on that and get back to you, but logging a warning for naive datetime is definitely a good idea.

**Comment by davebshow** [comment]
For reference, it seems that currently there are two datetime property types `goblin.properties.DateTime`, which expects UTC datetime, and `goblin.properties.NaiveDateTime`, which, of course, expects a naive datetime.

**Comment by rotten** [comment]
Interesting, thanks, I missed that!  Thanks for doing the fix too!

**Comment by davebshow** [comment]
Thank you for reporting. I'll close this for now, but this kind of property default behavior etc. will come under review in the near future.
